spring.application.name=ProjectBeachTennis


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.platform=mysql
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl_auto=update
logging.level.org.hibernate.type.descriptor.sql=TRACE

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG


spring.jackson.default-property-inclusion=non_null
spring.jackson.visibility.field=any

spring.profiles.active=dev